<?php

return [
  'PRODUCTION_STATUS' => env('PRODUCTION_STATUS'),
  'CLIENT_ID_TOKOPEDIA' => env('CLIENT_ID_TOKOPEDIA'),
  'APP_TOKOPEDIA_ID' => env('APP_TOKOPEDIA_ID'),
  'CLIENT_SECRET_TOKOPEDIA' => env('CLIENT_SECRET_TOKOPEDIA'),
  'REDIRECT_URI_TOKOPEDIA' => env('REDIRECT_URI_TOKOPEDIA'),
];